--- !ruby/object:PluginManager::Config
name: SpeedUpButton
authors:
- Yuri
version: 0.1.0.0
deps:
- :name: SpeedUpButtonPress
  :incompatible: true
psdk_compatibility_script: psdk.rb
retry_psdk_compatibility_after_plugin_load: false
added_files: []
